services:
  dev:
    image: epsicube-framework-test
    build:
      context: .
    volumes:
      - './:/app'
    working_dir: /app
    environment:
      HOME: /tmp
      XDG_CACHE_HOME: /tmp/.cache

